# enable bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

# style changes
export CLICOLOR=1

# required to use conda commands
# assumes conda is instlled at /anaconda3
export PATH="/anaconda3/bin:$PATH"

# required for using "conda activate"
. /anaconda3/etc/profile.d/conda.sh
